# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DurusaApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DurusaApp
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Analytics', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
end
